### ISSUE TITLE
Ontology file for SingleCell model

### ISSUE THREAD

**Issue by lzlniu** [HanwenXuTHU/BioTranslatorProject#2]
Hi,
When I am trying [Section 2.5 New Cell Type Discovery](https://github.com/HanwenXuTHU/BioTranslatorProject#section-25-new-cell-type-discovery), I found that an ontology file was required (default path is /data/xuhw/data/Ontology_data/cl.obo), what is cl.obo here and how can I get it (if necessary)?
Best

**Comment by HanwenXuTHU** [comment]
Please find them here. (https://github.com/HanwenXuTHU/BioTranslatorProject/tree/main/DataProcess/data)

**Comment by lzlniu** [comment]
Hi Hanwen,
I found cl.obo on https://github.com/obophenotype/cell-ontology and add it to your dir (DataProcess/data/).
But sill, an embeddings (cl.ontology.nlp.emb) was needed, is this (cl.ontology.nlp.emb) the output of the text encoder (input cl.ontology)?

**Comment by zhangjiahuan17** [comment]
@lzlniu 
Hi Zelin,

I met the same problem as you in running the code, do you know where the <cl.ontology.nlp.emb> file is generated?

Best
