### ISSUE TITLE
Question about input and output of BioTranslator

### ISSUE THREAD

**Issue by lzlniu** [HanwenXuTHU/BioTranslatorProject#4]
Hi Hanwen,
I'd successfully run through your analysis, thanks a lot for your support, I have some questions about the input and output:

As you mentioned in the email previously:
"R3: Our framework supports taking the text as input and then output the biological instances which are most closed to this textual descriptions. I suggest 1.Embedding the textual descriptions into the vector format as `BioTranslator_go_embeddings.pkl` (see [def get_BioTranslator_emb](https://github.com/HanwenXuTHU/BioTranslatorProject/blob/a011f20668a252763f5b26076450a2b8ffbb4f6e/SingleCell/BioTranslator/BioUtils.py#L989)) 2. prepare the biology instances features. 3. Feed both the textual description embeddings and biology instances into the model.pth files, which could output the probability for each biology instance being classified into one textual description and then you can find the biology instance with the highest probability. "

To my understanding, for example in [SingleCell](https://github.com/HanwenXuTHU/BioTranslatorProject/tree/a011f20668a252763f5b26076450a2b8ffbb4f6e#section-25-new-cell-type-discovery), [def get_BioTranslator_emb](https://github.com/HanwenXuTHU/BioTranslatorProject/blob/a011f20668a252763f5b26076450a2b8ffbb4f6e/SingleCell/BioTranslator/BioUtils.py#L989) uses the BioTranslator Text Encoder to embed the Gene Ontology terms. It loads the Gene Ontology terms from `cl.obo` using the `load_co_text` function. It then uses a pre-trained BERT model named `microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext` to encode each Gene Ontology term into a 768-dimensional vector. The encoded vectors are then stored in an ordered dictionary (default output file name is `BioTranslator_go_embeddings.pkl`) with their corresponding Gene Ontology terms in the input file (`cl.obo`) as keys.

It seems that this function is specifically designed to embed Gene Ontology terms and may not be suitable for embedding natural language text.

I wonder how to embed natural language from a text file rather than the `cl.obo` file? For example, input a description "expression of endothelial cell in lung" and a h5ad file which includes multiple single cell datasets, and the output is the single cell expression profile from the input that match the description most. What should I do to achieve this? Do you have code/script in the BioTranslator package for this kind of purpose?

Best,
Zelin

**Comment by HanwenXuTHU** [comment]
Our released codes provide the function to embed the definitions of ontology terms, which is exactly the format of natural language, isn't it? I think you can directly modify the get_BioTranslator_emb to input your text.

**Comment by lzlniu** [comment]
Ok I see, I will modify it a bit and come back to you later, thanks!

**Comment by lzlniu** [comment]
I just tried to load the model as below:
```
import torch
import biotranslator

model = torch.load('BioTranslator_sapiens_4_0.9.pth')
```
But got error:
```
~/Python-3.7/lib/python3.7/site-packages/biotranslator/metrics/_micro_auroc.py in 
      1 import numpy as np
----> 2 from _roc import compute_roc
      3 
      4 def micro_auroc(labels, preds):
      5     roc_micro = np.zeros(np.size(preds, 1))

ModuleNotFoundError: No module named '_roc'
```
Do you know what is the _roc here? I haven't find it, but the function was defined in the source code:
```
$ cd SingleCell/BioTranslator/
$ ls
BioConfig.py  BioMetrics.py  BioTrainer.py  __init__.py
BioLoader.py  BioModel.py    BioUtils.py    __pycache__
$ grep -r '_roc' *.py
BioMetrics.py:def compute_roc(labels, preds):
BioMetrics.py:        auroc = compute_roc(label_i, pred_i)
BioMetrics.py:        roc_auc_j = compute_roc(label_id, preds_id)
BioUtils.py:def compute_roc(labels, preds):
BioUtils.py:            auroc = compute_roc(unseen_labels, unseen_preds)
BioUtils.py:            roc_auc = compute_roc(inference_label[:, cl_i], inference_preds[:, cl_i])
```

**Comment by HanwenXuTHU** [comment]
Hi Zelin, sorry for this error! We are working on fixing this! For the model, I think you can definitely use it! Also, remember to include the text encoder for embedding texts.

**Comment by HanwenXuTHU** [comment]
> Hi Zelin, sorry for this error! We are working on fixing this! For the model, I think you can definitely use it! Also, remember to include the text encoder for embedding texts.

We have fixed this error! Please feel free to contact us if there is any other confusing thing.
